### ISSUE TITLE
podfile error when installing OLMKit

### ISSUE THREAD

**Issue by eliakorkmaz** [aapierce0/MatrixClient#3]
I tried to install podfile and i got error when installing `OLMKit`

```
[!] Error installing OLMKit
[!] /usr/local/bin/git clone https://matrix.org/git/olm.git /var/folders/_d/pdtpj8mx7vb4gv3ytgf3x4c00000gn/T/d20170328-10370-zo70go --template= --single-branch --depth 1 --branch 2.2.2

Cloning into '/var/folders/_d/pdtpj8mx7vb4gv3ytgf3x4c00000gn/T/d20170328-10370-zo70go'...
fatal: dumb http transport does not support shallow capabilities
```

**Comment by eliakorkmaz** [comment]
I solved the error that `dumb http transport` . Here is my podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MatrixClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MatrixClient
 #  pod 'OLMKit'
pod 'OLMKit', :git => 'https://matrix.org/git/olm.git', :commit => 'b0a010b1539fe6409f398bb209b156187c959c41'


  pod 'Realm'
  pod 'SwiftMatrixSDK', :git => 'https://github.com/aapierce0/matrix-ios-sdk.git', :branch => 'swiftyAPI'
#  pod 'SwiftMatrixSDK', :path => '../matrix-ios-sdk'


end
```

Then i installed pods and run the program.
But this time , Xcode throw an error about that it has not found the `SwiftMatrixSDK`

![ss](https://cloud.githubusercontent.com/assets/16090189/24426316/faa48e20-140f-11e7-8142-0caf9008b215.png)

**Comment by avery-pierce** [comment]
I pushed a new commit to the master branch that changes the pod for SwiftMatrixSDK to target a specific commit (https://github.com/aapierce0/matrix-ios-sdk/commit/ae745701478220480a652ce1723c6c40b1c8d769) rather than the swiftyAPI branch. Try pull that change and running `pod install` again.

If that doesn't work, try clearing the build folder by holding the option (alt) key down and choosing Product > Clean Build Folder...

**Comment by eliakorkmaz** [comment]
I added comment block to OLMKit block than I try again with `pod install` and It worked well for me.
